# Generated by Django 2.2.7 on 2019-11-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=10)),
                ('goal', models.CharField(max_length=10)),
                ('bar_tmp', models.CharField(max_length=21)),
                ('barcode', models.CharField(max_length=21)),
                ('kind', models.CharField(max_length=8)),
                ('purchase_date', models.DateField()),
                ('purchase_method', models.CharField(max_length=4)),
                ('attribute', models.CharField(max_length=8)),
                ('serial', models.CharField(max_length=6)),
                ('price', models.IntegerField()),
                ('user', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=5)),
                ('keeper', models.CharField(max_length=4)),
                ('code_place', models.CharField(max_length=8)),
                ('place', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=4)),
                ('detail', models.CharField(max_length=30)),
                ('out_date', models.DateField()),
            ],
        ),
    ]
