# Generated by Django 2.2.7 on 2019-12-07 23:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20191112_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stockaddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Stockrecrod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ways', models.CharField(max_length=1)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='记录时间')),
                ('newaddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new', to='backend.Stockaddress', verbose_name='库存地')),
                ('oldaddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old', to='backend.Stockaddress', verbose_name='库存地')),
                ('stocks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='backend.Stock', verbose_name='库存')),
            ],
        ),
    ]
