# Generated by Django 2.1 on 2019-12-17 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_stock_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='stock',
            name='attribute',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='barcode',
            field=models.CharField(default='', max_length=21),
        ),
        migrations.AlterField(
            model_name='stock',
            name='code_place',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='detail',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='stock',
            name='goal',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='keeper',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='stock',
            name='kind',
            field=models.CharField(default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='stock',
            name='number',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='stock',
            name='out_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='place',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='stock',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='serial',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='stock',
            name='user',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='stockrecrod',
            name='ways',
            field=models.CharField(default='', max_length=1),
        ),
    ]
