# Generated by Django 2.1 on 2019-12-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20191217_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockrecrod',
            name='newaddress',
        ),
        migrations.AddField(
            model_name='stockrecrod',
            name='olddetail',
            field=models.CharField(default='', max_length=30),
        ),
    ]
