# Generated by Django 2.1 on 2019-12-17 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20191217_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='out_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='stock',
            name='purchase_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
